<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-wrap items-end justify-between gap-4">
            <div><p class="text-sm font-medium text-violet-600">Overview</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-slate-900">{{ $greeting }}, {{ Str::before(Auth::user()->name, ' ') }}</h2><p class="mt-1 text-sm text-slate-500">Here is what is happening across your office stock today.</p></div>
            {{-- <p class="text-sm text-slate-500">{{ now()->format('l, d F Y') }}</p> --}}
        </div>
    </x-slot>

    <div class="space-y-6 px-4 py-8 sm:px-6 lg:px-8">
        @include('partials.flash')
        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <a href="{{ route('admin.requests.index', ['status' => 'PENDING']) }}" class="group rounded-2xl bg-violet-700 p-5 text-white shadow-lg shadow-violet-900/10 transition hover:-translate-y-0.5">
                <div class="flex items-start justify-between"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-white/15">↗</span><span class="text-xs font-semibold text-violet-200">Needs review</span></div><p class="mt-6 text-sm text-violet-200">Pending requests</p><p class="mt-1 text-3xl font-bold">{{ $pendingCount }}</p><p class="mt-4 text-xs text-violet-200 group-hover:text-white">Open request queue &rarr;</p>
            </a>
            <a href="{{ route('admin.items.index') }}" class="group rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:ring-violet-300"><div class="flex items-start justify-between"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-100 text-emerald-700">□</span><span class="text-xs font-semibold text-emerald-600">In catalogue</span></div><p class="mt-6 text-sm text-slate-500">Stock items</p><p class="mt-1 text-3xl font-bold text-slate-900">{{ $itemCount }}</p><p class="mt-4 text-xs text-slate-500 group-hover:text-violet-700">Manage inventory &rarr;</p></a>
            <a href="{{ route('admin.items.index') }}" class="group rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:ring-violet-300"><div class="flex items-start justify-between"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-100 text-amber-700">!</span><span class="text-xs font-semibold text-amber-600">Attention</span></div><p class="mt-6 text-sm text-slate-500">Low stock alerts</p><p class="mt-1 text-3xl font-bold text-slate-900">{{ $lowStockItems->count() }}</p><p class="mt-4 text-xs text-slate-500 group-hover:text-violet-700">Review alerts &rarr;</p></a>
            <a href="{{ route('admin.transactions.index') }}" class="group rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:ring-violet-300"><div class="flex items-start justify-between"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-sky-100 text-sky-700">▤</span><span class="text-xs font-semibold text-sky-600">All locations</span></div><p class="mt-6 text-sm text-slate-500">Units on hand</p><p class="mt-1 text-3xl font-bold text-slate-900">{{ number_format($totalBalance) }}</p><p class="mt-4 text-xs text-slate-500 group-hover:text-violet-700">View stock ledger &rarr;</p></a>
        </section>

        <section class="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
            <div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
                <div class="flex items-start justify-between gap-4"><div><h3 class="text-lg font-bold text-slate-900">Quick actions</h3><p class="mt-1 text-sm text-slate-500">Keep the stock desk moving.</p></div><span class="text-xs font-semibold uppercase tracking-wider text-slate-400">Shortcuts</span></div>
                <div class="mt-6 grid gap-3 sm:grid-cols-3"><a href="{{ route('admin.items.create') }}" class="rounded-xl border border-slate-200 p-4 transition hover:border-violet-300 hover:bg-violet-50"><span class="text-xl text-violet-600">+</span><span class="mt-3 block text-sm font-semibold text-slate-900">Add item</span><span class="mt-1 block text-xs text-slate-500">Create a catalogue item</span></a><a href="{{ route('admin.qrcode') }}" class="rounded-xl border border-slate-200 p-4 transition hover:border-violet-300 hover:bg-violet-50"><span class="text-xl text-violet-600">⌁</span><span class="mt-3 block text-sm font-semibold text-slate-900">Display QR</span><span class="mt-1 block text-xs text-slate-500">Open the employee form</span></a><a href="{{ route('admin.transactions.export') }}" class="rounded-xl border border-slate-200 p-4 transition hover:border-violet-300 hover:bg-violet-50"><span class="text-xl text-violet-600">↓</span><span class="mt-3 block text-sm font-semibold text-slate-900">Export ledger</span><span class="mt-1 block text-xs text-slate-500">Download an Excel report</span></a></div>
            </div>
            <div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="flex items-start justify-between"><div><h3 class="text-lg font-bold text-slate-900">Low stock</h3><p class="mt-1 text-sm text-slate-500">Items that need a restock plan.</p></div><a href="{{ route('admin.items.index') }}" class="text-sm font-semibold text-violet-600">View all</a></div><div class="mt-5 space-y-4">@forelse($lowStockItems->take(4) as $item)<div class="flex items-center justify-between gap-4"><div class="min-w-0"><p class="truncate text-sm font-semibold text-slate-900">{{ $item->name }}</p><p class="text-xs text-slate-500">{{ $item->item_code }} &middot; minimum {{ $item->min_stock }}</p></div><span class="shrink-0 rounded-full bg-red-50 px-3 py-1 text-sm font-bold text-red-600">{{ $item->current_balance }} left</span></div>@empty<p class="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">All tracked items are above their minimum level.</p>@endforelse</div></div>
        </section>

        <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="flex items-center justify-between"><div><h3 class="text-lg font-bold text-slate-900">Recent activity</h3><p class="mt-1 text-sm text-slate-500">The latest movement recorded in the stock ledger.</p></div><a href="{{ route('admin.transactions.index') }}" class="text-sm font-semibold text-violet-600">Open ledger &rarr;</a></div><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[640px] text-left text-sm"><thead><tr class="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-400"><th class="pb-3 font-semibold">Activity</th><th class="pb-3 font-semibold">Type</th><th class="pb-3 font-semibold">Quantity</th><th class="pb-3 font-semibold">Balance after</th><th class="pb-3 text-right font-semibold">When</th></tr></thead><tbody>@forelse($recentTransactions as $transaction)<tr class="border-b border-slate-100 last:border-0"><td class="py-4"><p class="font-semibold text-slate-900">{{ $transaction->item->name }}</p><p class="text-xs text-slate-500">{{ $transaction->note ?: 'Stock movement' }}</p></td><td class="py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $transaction->type === 'IN' ? 'bg-emerald-50 text-emerald-700' : 'bg-orange-50 text-orange-700' }}">{{ $transaction->type }}</span></td><td class="py-4 font-semibold text-slate-700">{{ $transaction->quantity }} {{ $transaction->item->unit }}</td><td class="py-4 text-slate-600">{{ $transaction->balance_after }}</td><td class="py-4 text-right text-slate-500">{{ $transaction->created_at->diffForHumans() }}</td></tr>@empty<tr><td colspan="5" class="py-8 text-center text-slate-500">No stock activity has been recorded yet.</td></tr>@endforelse</tbody></table></div></section>
    </div>
</x-app-layout>
